FRONTENDSCHOOL10/sibi11jo

- src/styles/style.scss
- [] 새로운 기능 추가
- [] 버그 수정
- [] CSS 등 사용자 UI 디자인 변경
- [] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [] 코드 리팩토링
- [] 주석 추가 및 수정
- [] 문서 수정
- [] 테스트 추가, 테스트 리팩토링
- [] 빌드 부분 혹은 패키지 매니저 수정
- [] 파일 혹은 폴더 삭제
resolves #
> 🎉 init: 초기 설정

- index.html
- src/components/template.html
- src/styles/abstracts/_mixins.scss
- src/styles/abstracts/_variables.scss
- src/styles/base/_common.scss
- src/styles/base/_iconfonts.scss
- src/styles/components/_badge.scss
- src/styles/components/_button.scss
- src/styles/components/_checkbox.scss
- src/styles/components/_textInput.scss
- src/styles/style.scss
- components 폴더 내 template.html 추가
- scss 추가 (Badge, Button, Checkbox, Radio, Input)
- 공통적으로 사용되는 컴포넌트 중, 우선적으로 Badge, Button, Checkbox, Radio, Input을 생성하였습니다.
- 스크럼 회의 때, 함께 살펴보며 앞으로의 작업 방향에 대해 함께 의논해보면 좋을 것 같습니다.
- 🎨 feat: components 추가
> 🎨 feat: components 추가

- src/components/template.html
- src/styles/components/_productDetails.scss
- src/styles/components/_productInquiry.scss
- src/styles/components/_productReview.scss
- src/styles/components/_productTab.scss
- src/styles/components/_sectionHeader.scss
- src/styles/style.scss
- productDetails 추가
- productInquiry 추가
- productReview 추가
- productTab 추가
- sectionHeader 추가
resolves #16
> 💙 Component : 생성 및 개선

- .env
- package-lock.json
- package.json
- src/api/pocketbase.js
- src/layout/footer.html
- pocketbase npm 설치
- 환경 변수(기본 url) 설정
resolves #14
> ⚙️ Ci : pocketbase 기초 설정

- src/components/template.html
- src/styles/components/_productDetails.scss
- src/styles/components/_productInquiry.scss
- src/styles/components/_productReview.scss
- src/styles/components/_productTab.scss
- src/styles/components/_sectionHeader.scss
- productTab.scss
- productDetails.scss
- productReview.scss
- productInquiry.scss
resolves #23
> 💙 Component : 컴포넌트 수정(마크업 및 파일이름 변경)

- src/pages/login.html
- src/pages/register.html
- src/styles/pages/_login.scss
- src/styles/pages/_register.scss
- 로그인, 회원가입 페이지 추가
resolves #5
> 🧡 Markup : 로그인, 회원가입 페이지 추가

- src/components/template.html
- src/styles/components/_productDetails.scss
- productDetails.scss
resolves #29
> 💙 Component : product details 컴포넌트 수정

- src/pages/cart.html
- src/styles/components/_cartList.scss
- src/styles/components/_cartResult.scss
- src/styles/pages/_cart.scss
- src/styles/style.scss
- cart.html
- _cart.scss
- _cartList.scss
- _cartResult.scss
- style.scss
resolves #17
> 💙 Component : cart page component 생성 및 레이아웃

- index.html
- main.js
- src/components/template.html
- src/layout/footer/footer.html
- src/layout/header/header.js
- src/pages/cart.html
- src/pages/details.html
- src/pages/login.html
- src/pages/product.html
- src/pages/register.html
- src/styles/pages/_main.scss
- index 수정 (메인 페이지)
- html ko-KR 수정
- 파비콘 추가
- a링크 경로 수정
resolves #41
> ✅ Test : 페이지 전환 테스트 진행 중

- src/layout/header/header.html
- src/styles/base/_common.scss
- src/styles/components/_productDetails.scss
- src/styles/layout/_header.scss
- src/styles/pages/_product.scss
- 로고 관련 수정
- 내비게이션 포커스 관련 수정
- 카테고리 메뉴 드롭다운 추가
- 전체 스크롤바 관련 스타일 수정
resolves #44
> ♻️ Refactor : 헤더 리팩토링

- main.js
- main.js에서 swiper.js import 추가
resolves #51
> 💚 Docs : main.js 파일 수정

- index.html
- src/api/pocketbase.js
- src/components/template.html
- src/layout/header/header.html
- src/layout/header/header.js
- src/pages/main/main.html
- src/pages/main/swiper.js
- src/pages/product/product.html
- src/styles/abstracts/_variables.scss
- src/styles/base/_iconfonts.scss
- src/styles/pages/_product.scss
- vite.config.js
- scss 및 세미콜론 수정
- html ko-KR로 통일
- vite.config outDir
resolves #54
> 💄 Style : scss 및 세미콜론 수정

- main.js
- src/layout/header/header.html
- src/pages/product/product.html
- src/styles/pages/_product.scss
- product.html: 태그 클래스명 추가
- header.html:  index.html 경로 수정
- 
resolves #57
> 🧡 Markup : html 문서 수정

- src/styles/pages/_main.scss
-swiper 부분 창 작아질 경우 이미지 센터에 안 맞는 문제 해결 -> img에 width, height 100% 지정
resolves #59
> 💄 Style : _main.scss 수정

- src/pages/cart/cart.html
- src/styles/components/_cartList.scss
- src/styles/components/_cartResult.scss
- src/styles/pages/_cart.scss
- cart.html
- _cartList.scss
- _cartResult.scss
- _cart.scss
resolves #33
> 🧡 Markup : cart.html 마크업 및 스타일링

- src/pages/main/swiper.js
> ♻️ Refactor : swiper keyboard 컨트롤

- src/pages/cart/cart.html
- src/pages/product/product.html
- src/styles/pages/_cart.scss
- src/styles/pages/_product.scss
- main 태그에 공통 클래스 'page' 추가
- 타이틀 레이아웃 통일
- cart.html 클래스명 수정
resolves #70
> ♻️ Refactor : 제품 목록, 장바구니 페이지 코드 리팩토링 및 타이틀 위치 통일

- index.html
- src/pages/main/main.html
- src/styles/pages/_main.scss
index.html, main.html, main.scss 수정
- position: sticky 속성으로 화면 특정 영역 출력
- media query로 뷰포트 너비가 좁아지면 사라지게 만들기
resolves #75
> Markup : side-bar 보이는 영역 조절

- src/components/template.html
- src/styles/components/_button.scss
> 💙 Component : 상품 수량 버튼 추가

- main.js
- src/api/defaultAuthData.js
- src/layout/header/header.html
- src/layout/header/header.js
- src/pages/login/login.html
- src/pages/login/login.js
- src/styles/layout/_header.scss
- src/styles/pages/_login.scss
- 로그인 유효성 검사
- 로그인 / 로그아웃 기능 구현
-
resolves #88
> 🎨 Feat : 로그인 기능 구현

- src/pages/main/main.html
- src/pages/main/swiper.js
- src/styles/pages/_main.scss
swiper.js : .product-list__swiper 컴포넌트 추가
_main.html :  코드 수정
_main.scss : swiper-button스타일 변경
resolves #
> 🎨 Feat : 메인 페이지 제품 리스트 스와이퍼 추가

- src/pages/main/close.js
- src/pages/main/main.html
- src/pages/main/close.js 폴더 생성해서 기능 추가
- main.html 에 script 태그 삽입
resolves #
> 🎨 Feat : 팝업 광고 닫기 버튼 기능 추가

- index.html
- src/pages/cart/cart.html
- src/pages/main/main.html
- src/pages/productDetail/details.html
- src/styles/components/_cartList.scss
- src/styles/pages/_main.scss
- index.html
- cart.html
- cartList.scss
- main.html
- main.scss
- details.html
resolves #81
> ♻️ Refactor : 수정된 상품 수량 버튼 페이지에 적용

- src/api/getPbImageURL.js
- src/pages/product/product.html
- src/pages/product/product.js
- src/styles/components/_card.scss
- pocketbase 데이터 렌더링
- 데이터 수 표시
- 정렬 버튼 클릭 시 데이터 정렬 기능 구현
- card 컴포넌트 height 값 수정
resolves #77
> 🎨 Feat : 제품 목록 페이지 데이터 렌더링 및 정렬 기능 구현

- src/pages/cart/cart.html
- src/pages/cart/cart.js
- src/styles/components/_cartList.scss
- cart.html
- cart.js
- _cartList.scss
resolves #97
> 🎨 Feat : cart List의 button toggle, checkbox 전체 선택 구현

- index.html
- main.js
- src/pages/main/swiper.js
- src/styles/pages/_main.scss
- _main.scss 파일 수정
- main.html 변경사항 index.html 에 적용
- main.js에 close.js 파일 import
- swiper.js 주석 삭제
- _main.scss 커밋이 적용되지 않아 생긴 문제였습니다. 파일 수정 완료 후 index.html 코드도 변경하였습니다.
resolves #
> 🦋 BugFix : 메인페이지 ui 깨짐 수정

- main.js
- src/layout/header/header.js
- src/pages/login/login.js
- src/pages/register/register.html
- src/pages/register/register.js
> 🎨 Feat : 회원가입/탈퇴 기능 구현

- src/components/template.html
- src/styles/components/_address.scss
- src/styles/components/_order.scss
- src/styles/style.scss
- _address.scss
- _order.scss
- style.scss
resolves #106
> 💙 Component : cart page 모달창 만들기

- src/layout/header/header.js
- src/pages/register/register.html
- 회원가입 필수 입력 요소 required 추가
- 미구현 버튼 disabled 처리
resolves #
> ✅ Test : 회원가입, 탈퇴 임시 코드 수정

- src/layout/header/header.js
- src/pages/login/login.html
- src/pages/register/register.html
- 로그인, 회원가입 힌트 텍스트 수정
- 회원 탈퇴 코드 수정
resolves #
> ✅ Test : 회원 탈퇴 코드 수정

- src/pages/cart/cart.html
- src/pages/cart/modal.js
- src/styles/components/_address.scss
- src/styles/components/_order.scss
- src/styles/components/_overlay.scss
- src/styles/pages/_cart.scss
- src/styles/style.scss
- overlay 활성화
- 5초 후 메인 페이지로 이동
- 배송지를 입력 후 저장을 누르면 배송지 변경
- cart.html
- modal.js
- _address.scss
- _order.scss
- _overlay.scss
- _cart.scss
resolves #112
> 🎨 Feat : 장바구니 페이지

- src/pages/product/accordion.js
- src/pages/product/product.html
- src/pages/product/product.js
- src/styles/components/_accordion.scss
- src/styles/pages/_product.scss
- 아코디언 바에서 체크박스 선택시 필터링 기능 구현(카테고리, 배송, 혜택, 유형)
- 아코디언 애니메이션 기능 추가
- 아코디언 title(필터, 초기화 버튼) 추가
- 아코디언 position: sticky 추가
resolves #99
> 🎨 Feat : 필터링 기능 구현  및 아코디언 수정

- src/pages/product/product.html
- src/pages/product/product.js
- src/styles/components/_accordion.scss
- 가격 필터링 기능 구현
- 필터링 초기화 기능 구현
- 필터링 조건 처리 수정
resolves #118
> 🎨 Feat : 아코디언 가격 필터링, 초기화 기능 구현 및 수정

- src/components/template.html
- src/pages/productDetail/details.html
- src/styles/components/_productInquiryModal.scss
- src/styles/components/_productReviewModal.scss
- src/styles/style.scss
- _productInquiryModal.scss
- _productReviewModal.scss
- style.scss
- details.html
resolves #26
> 💙 Component : 상품후기, 상품문의 modal 컴포넌트 제작

- src/components/template.html
- src/styles/pages/_main.scss
- template.html에 코드 추가
- main.scss 의 display:none 코드 삭제
resolves #
> Component : 장바구니 추가 모달 컴포넌트 생성

- src/components/template.html
- src/styles/components/_modal.scss
- src/styles/style.scss
- _modal.scss
- style.css
resolves #138
> ♻️ Refactor : modal 컴포넌트

- src/components/template.html
- src/lib/timer.js
- src/pages/cart/order.js
- src/pages/productDetail/details.html
- src/pages/productDetail/details.js
- src/pages/productDetail/inquiry.js
- src/pages/productDetail/review.js
- src/styles/components/_modal.scss
- src/styles/components/_productInquiryModal.scss
- src/styles/components/_productReviewModal.scss
- src/styles/pages/_details.scss
1. product review modal
2. product inquiry modal
3. timer 함수 생성 및 파일 분리
resolves #132
> 🎨 Feat : modal handle 및 함수 생성

- src/pages/product/accordionToggle.js
- src/pages/product/count.js
- src/pages/product/product.html
- src/pages/product/product.js
- product.js 함수 분리 -> accordionToggle.js / count.js 파일 생성
- product.js에 style.scss, header.js, footer.js import 추가
resolves #135
> 📂 create : accordionToggle.js / count.js 파일 생성

- src/pages/cart/cart.html
- src/pages/cart/cart.js
- src/pages/cart/order.js
- src/pages/cart/toggle.js
- src/styles/components/_address.scss
- src/styles/pages/_cart.scss
- cart.html
- cart.js
- checkbox.js
- order.js
- toggle.js
- _address.scss
- _cart.scss
resolves #142
> ♻️ Refactor : cart page 파일 분리

- src/pages/main/main.html
- src/pages/main/main.js
- src/pages/productDetail/details.html
refactor: index.html에 연결된 main.js 파일의 import 모듈 이동
* 해당파일의 남아있는 main페이지 관련 코드 모두 삭제해도 됩니다.
* src하위의 main.js 폴더에 남아있는 main페이지 관련 코드 모두 삭제해도 됩니당
resolves #
> create: main폴더 안 main.js 파일 생성 후 모듈 경로 수정

- src/layout/header/header.js
- src/pages/login/login.html
- src/pages/login/login.js
- src/pages/register/register.html
- src/pages/register/register.js
- src/styles/components/_modal.scss
- src/styles/layout/_header.scss
- src/styles/pages/_register.scss
- 헤더 카테고리 메뉴 키보드 제어 추가
- 모달 추가
- 기타 수정
- 아이디/이메일 중복 확인 기능 (X)
resolves #
> ✅ Test : 헤더, 로그인, 회원가입

- src/pages/cart/cart.html
- src/pages/cart/cart.js
- src/pages/cart/checkbox.js
- src/pages/cart/index.js
- src/pages/cart/price.js
- cart.html
- cart.js
- checkbox.js
- price.js
- 
resolves #147
> 🎨 Feat : checkbox handler

- src/pages/cart/cart.html
- src/pages/cart/cart.js
- src/pages/cart/checkbox.js
- src/pages/cart/delete.js
- src/pages/cart/toggle.js
- cart.html
- cart.js
- checkbox.js
- delete.js
- toggle.js
resolves #156
> ♻️ Refactor : 아이템 리스트의 갯수에 따른 전체갯수 변경

- src/pages/main/getPbData.js
- src/pages/main/productCard.js
- 상품 디테일 페이지 경로 이동,
- 데이터 베이스 가져오는 함수 컴포넌트화
- [] 새로운 기능 추가
- [] 파일 혹은 폴더명 수정
- [] 문서 수정
- [] 버그 수정
- [] CSS 등 사용자 UI 디자인 변경
- [] 코드에 영향을 주지 않는 변경사항(주석 추가 및 수정, 오타 수정, 탭 사이즈 변경, 변수명 변경)
- [] 파일 혹은 폴더 삭제
- [] 빌드 부분 혹은 패키지 매니저 수정
resolves #
> ✅ Test : 메인 페이지 상품 링크 디테일 페이지로 수정

- src/lib/regExp.js
- src/pages/register/register.html
- src/pages/register/register.js
- 아이디/이메일 중복 확인 기능 추가
- 휴대폰 번호 입력 시 하이픈 자동 입력 기능 추가
- 이용약관 동의 필수 사항 조건 처리
resolves #151
> ♻️ Refactor : 회원가입 리팩토링

- src/pages/product/product.js
- src/pages/productDetail/details.html
- src/pages/productDetail/details.js
- src/pages/productDetail/productRender.js
- src/styles/components/_productDetails.scss
- details.html
- details.js
- product.js
- productRender.js
- _productDetails.scss
resolves #158
> ✅ Test : details 로 데이터 불러오기

- src/lib/priceHandler.js
- src/pages/productDetail/details.js
- src/pages/productDetail/productRender.js
- priceHandler.js
- details.js
- productRender.js
resolves #169
> ♻️ Refactor : details 페이지 보강

- src/pages/product/createProductCard.js
- src/pages/product/filter.js
- src/pages/product/product.js
- src/pages/product/sort.js
- product.js 함수 분리
- createProductCard.js: 카드 생성부
- filter.js: 아코디언 필터 받아오는 부분
- sort.js: 정렬 버튼
resolves #172
> ♻️ Refactor : product.js 코드 리팩토링

- src/lib/priceHandler.js
- priceHandler.js
resolves #171
> ♻️ Refactor : 제품 갯수에 따른 최종 가격 변경

- src/pages/product/createProductCard.js
- a태그 경로 detail 페이지로 수정
resolves #176
> 💙 Component : productCard 컴포넌트 수정

- src/pages/product/addCart.js
- 담기 버튼 클릭할 때마다 카운트 누적 문제 해결
resolves #179
> 🦋 BugFix : addcart 모달 수량 카운트 부분 수정

- README.md
> 💚 Docs : README.md 내용 추가

- src/pages/product/addCart.js
- src/pages/product/bubble.js
- src/pages/product/product.html
- src/styles/components/_bubble.scss
- src/styles/pages/_product.scss
💄 Style : bubble.scss / product.scss 수정
- 버블 활성화 시 위치 설정
🦋 BugFix : bubble 데이터 관련 버그 수정
resolves #182
> 💄 Style : bubble.scss / product.scss 수정

- src/components/template.html
- src/styles/components/_address.scss
- src/styles/components/_modal.scss
- _address.scss
- _modal.scss
resolves #187
> ♻️ Refactor : component 수정

- src/components/template.html
- src/pages/product/product.html
- src/styles/components/_accordion.scss
- src/styles/components/_button.scss
- src/styles/components/_card.scss
- src/styles/components/_cartList.scss
- src/styles/components/_productTab.scss
- src/styles/components/_textInput.scss
- src/styles/layout/_header.scss
- src/styles/pages/_details.scss
- src/styles/pages/_main.scss
- 스크롤 헤더 nav 메뉴 높이 수정
- 포커싱 통일 (일부 버튼, 제품 카드)
- 상세 페이지 탭 버튼 수정 (높이 및 스타일)
- 장바구니 리스트 스타일 수정
- 제품 페이지 아코디언 / 추천순 툴팁 스타일 수정
resolves #198
> 💄 Style : 페이지별 스타일 수정

- index.html
- src/pages/main/swiper.js
- src/styles/pages/_main.scss
> ✅ Test : 최근 본 상품 스와이퍼 테스트

- src/pages/cart/addCartEvent.js
- src/pages/cart/cart.html
- src/pages/cart/cart.js
- src/pages/cart/checkbox.js
- src/pages/cart/delete.js
- src/pages/cart/order.js
- src/pages/cart/price.js
- src/pages/cart/toggle.js
> 🎨 Feat : cartpage 장바구니 담기 구현

- src/pages/cart/addCartEvent.js
- src/pages/cart/cart.html
- src/pages/cart/checkbox.js
- src/pages/cart/delete.js
- src/pages/cart/order.js
- src/pages/cart/toggle.js
- src/pages/main/productSwiperRender.js
- src/pages/main/sidebarData.js
- src/styles/components/_cartList.scss
- src/styles/components/_productInquiryModal.scss
- src/styles/components/_productReviewModal.scss
> ♻️ Refactor : cart page 리팩토링

- index.html
- src/pages/main/main.js
- src/pages/main/swiper.js
- src/styles/pages/_main copy.scss
> ♻️ Refactor : 메인 페이지 스와이퍼 수정

- src/pages/main/sidebarData.js
- src/pages/product/product.html
- src/styles/components/_button.scss
- [] 새로운 기능 추가
- [] 파일 혹은 폴더명 수정
- [] 문서 수정
- [] 버그 수정
- [] 코드 리팩토링
- [] 테스트 추가, 테스트 리팩토링
- [] CSS 등 사용자 UI 디자인 변경
- [] 코드에 영향을 주지 않는 변경사항(주석 추가 및 수정, 오타 수정, 탭 사이즈 변경, 변수명 변경)
- [] 파일 혹은 폴더 삭제
- [] 빌드 부분 혹은 패키지 매니저 수정
resolves #
> [bugfix/main] 버그 픽스

- src/layout/header/header.js
- src/styles/pages/_login.scss
- src/styles/pages/_main.scss
- [] 새로운 기능 추가
- [] 파일 혹은 폴더명 수정
- [] 문서 수정
- [] 버그 수정
- [] 코드 리팩토링
- [] 테스트 추가, 테스트 리팩토링
- [] CSS 등 사용자 UI 디자인 변경
- [] 코드에 영향을 주지 않는 변경사항(주석 추가 및 수정, 오타 수정, 탭 사이즈 변경, 변수명 변경)
- [] 파일 혹은 폴더 삭제
- [] 빌드 부분 혹은 패키지 매니저 수정
resolves #
> bugfix : header

- README.md
> 💚 Docs : Update README.md
